css-scroll-api/UseCases.md

Started on the Houdini wiki but collaboration there is harder than on GitHub (eg. due to access permissions, and lack of support for copying markdown directly from existing github discussions).

Add scroll-api use cases

---

css-typed-om/Overview.bs

Add note about LengthValues clamping at use time.

---

css-typed-om/Overview.bs

[CSS Typed OM] Add misssing animation, multi-column and transform properties to table of accepted types

---

css-typed-om/Overview.bs

[css-typed-om] Also make KeywordValue's keywordValue attribute readonly

---

css-typed-om/Overview.bs

(https://github.com/w3c/css-houdini-drafts/issues/268)
@tabatkins ptal, I'm really unsure of how to go about writing this correctly.

[css-typed-om] Attempt at serialization section.

---

worklets/Overview.bs

Primarily based on:
https://html.spec.whatwg.org/#set-up-a-worker-environment-settings-object
Inherits a couple more things from the document.
Fixes #227 - inherits the HTTPS state from document

[worklets] Fixes the setup of the inside setttings object for worklets.

---

css-paint-api/Overview.bs

[css-paint-api] Fix image placeholder example

---

worklets/Overview.bs

[worklets] Misc. edits from @domenic review.

---

css-properties-values-api/Overview.bs

remove duplicated "&lt;" in css-properties-values-api.

[css-properties-values-api] remove duplicated "&lt;"

---

css-typed-om/Overview.bs

@shans and @tabatkins could you take a look?

Add Naina Raisinghani to Typed OM editors

---

css-typed-om/Overview.bs

Add note about case-insensitivity of properties on StylePropertyMapReadOnly

---

css-typed-om/Overview.bs

Add serialization procedures of left/right/top/bottom.
@shans PTAL?

Add serialization for left/right/top/bottom

---

css-layout-api/Overview.bs

Spotted these minor errors when reading through some of this draft...

Minor language corrections

---

css-typed-om/Overview.bs

Add description for StylePropertyMapReadOnly::getAll

---

css-typed-om/Overview.bs

Would resolve #550 if it's actually a problem.
@tabatkins PTAL, thanks!

[css-typed-om] Remove CSSKeywordValue stringifier

---

css-typed-om/Overview.bs

Change .to to return CSSUnitValue

---

css-typed-om/Overview.bs

CSSURLImageValue should serialize url with quotes

---

css-typed-om/Overview.bs

Setting/modifiying CSSUnitValue.unit should be consistent on Error thrown

---

css-typed-om/Overview.bs

Add example of normalizing N-ary operators

---

css-typed-om/Overview.bs

Setting/modifiying value to empty string throws a TypeError

---

css-typed-om/Overview.bs

@tabatkins PTAL? Another option would be saying its a "mix"
Fixes #495

Express that tokens can be a mix of DOMStrings and CSSVariableReferenceValues

---

css-typed-om/Overview.bs

Expose StylePropertyMap.set on Window only.

---

css-typed-om/Overview.bs

StylePropertyMap.set should throw when setting multiple values to non list prop

---

css-typed-om/Overview.bs

CSSTranslation.z shouldn't allow percents

---

css-typed-om/Overview.bs

Closes #573 
Hi @tabatkins, PTAL

Clarify bulleted list about CSSNumericValues

---

css-typed-om/Overview.bs

Cater for RangeError caused by dividing by 0

---

css-typed-om/Overview.bs

Make CSSNumericArray an iterable

---

css-typed-om/Overview.bs

issue #534 
Hi @tabatkins, PTAL

Ensure at least one transform component in CSSTransformValue

---

css-typed-om/Overview.bs

Add table of what popular properties normalize to

---

css-typed-om/Overview.bs

Add match references

---

css-typed-om/Overview.bs

Move it from `CSSImageValue` to `CSSResourceValue`
Fixes #628

Move comment about resources that don't need network request

---

css-typed-om/Overview.bs

Add units of `CSSImageValue`.intrinsic{Width,Height}

---

css-typed-om/Overview.bs

Fixes #631 .
Hi @tabatkins , PTAL.

Add description of CSSURLImageValue getter

---

css-typed-om/Overview.bs

Fixes #677 and #678 .
Hi @tabatkins PTAL

Enforce ordering on order of operations

---

css-typed-om/Overview.bs

Be more explicit about throwing RangeError in CSSMathValue.invert()

---

css-typed-om/Overview.bs

Add some reification

---

css-typed-om/Overview.bs

Add some more reification

---

css-layout-api/EXPLAINER.md

found a typo in one of the code examples

frgment -> fragment

---

css-properties-values-api/Overview.bs

[css-properties-values-api] Make 'inherits' required.

---

css-properties-values-api/Overview.bs

[css-properties-values-api] Explain how relative URLs work.

---

css-animationworklet/Overview.bs

Previously the callback type was VoidFunction which is incorrect since it is expected to
return the new instance.

[css-animationworklet] Fiox animator ctor callback type

---

css-properties-values-api/Overview.bs

[css-properties-values-api] Remove reference to issue #118.

---

css-properties-values-api/Overview.bs

Generating said token stream is now described by § 4.5. Substitution.

[css-properties-values-api] Remove Issue 1.

---

worklets/Overview.bs

See also https://github.com/heycam/webidl/pull/423. (Found from https://github.com/web-platform-tests/wpt/pull/18382)

Add explicit [Exposed]

---

css-typed-om/Overview.bs

Required after heycam/webidl#750. (Found from web-platform-tests/wpt#18382)

[css-typed-om] Add default dictionary value

---

css-typed-om/Overview.bs

minor edit: missing word

---

worklets/Overview.bs

Required after heycam/webidl#750. (Found from web-platform-tests/wpt#18382)

[worklets] Add default dictionary value

---

css-typed-om/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/12454

[css-typed-om] Add missing steps to reify oklab() and oklch() 

---

css-typed-om/Overview.bs

I'm only part-way through implementing the spec, but I wanted to open this PR now while I remember. (If I come across more before this gets merged, I'll add them in subsequent commits.)

[css-typed-om-1] Correct a couple of typos
