w3c/css-houdini-drafts

- css-typed-om/Overview.bs
Apparently I actually did this last year and completely forgot!
Keywords are now just a wrapper for a String.
I also started a table for which properties can take which StyleValues, but got stuck with how to make a table in bikeshed. Any advice?
> Adjust spec for KeywordValue to be wrapper for string, add table of properties to StyleValue types.

- css-layout-api/Overview.bs
> [css-layout-api] Fix a minor typo

- css-typed-om/Overview.bs
> Add prose regarding SyntaxError

- css-paint-api/Overview.bs
The spec uses the term "scratch bitmap", which links to
https://html.spec.whatwg.org/multipage/scripting.html#scratch-bitmap
which is a broken link.
I believe this is meant to point to the definition of "output bitmap" in that HTML spec, i.e. it should be pointing to:
https://html.spec.whatwg.org/multipage/scripting.html#output-bitmap
...and it should be using the consistent term (with the word "output" instead of "scratch").
Not sure if the HTML spec changed out from under us or what, but anyway, this should get us back to a state with working links.
> s/scratch bitmap/output bitmap/ to fix broken link

- css-layout-api/README.md
Fixing a few instances of common "it's" typo.
"it's" = a contraction of "it is"
"its" = the possessive version of the word
This text wants the latter.
> Fix grammar typo (s/it's/its/, for posessive form)

- css-typed-om/Overview.bs
https://github.com/w3c/css-houdini-drafts/issues/245
rotate3d syntax in old OM is "rotate3d(x, y, z, a)", but in Typed OM it is Constructor(angle, x, y, z)
> Change order of CSSRotation arguments to be consistent with rotate3d.

- css-properties-values-api/Overview.bs
Tiny pull request to make register/unregisterProperty functions on the CSS interface to be static.
See @tabatkins' comment and the discussion at [1].
[1]: https://github.com/w3c/css-houdini-drafts/issues/216#issuecomment-224766248
> Fix register/unregisterProperty on CSS interface to be static.

- worklets/Overview.bs
@domenic A first pass of fixing worklets import using a shared cache. Wording for the cache is very similar to the module map in html, and seems ok?
Not happy with "fetched module map" naming.
cc/ @bzbarsky @annevk
> [worklets] First pass of fixing import for worklets.

- css-typed-om/Overview.bs
I also moved CSSTokeStreamValue down into the "CSSStyleValue subclasses" section since it is a subclass of CSSStyleValue.
> [css-typed-om] Make attributes readonly in CSSTokenStreamValue, CSSNumberValue and CSSLengthValues

- css-typed-om/Overview.bs
This change makes CSSSkew more consistent with CSSRotation.
> [css-typed-om] Add constructor for CSSSkew with CSSAngleValues

- css-typed-om/Overview.bs
This makes them more consistent with CSSPerspective and CSSTranslation, which store their length members and CSSLengthValues.
> [css-typed-om] Make CSSSkew and CSSRotation store their angle members as CSSAngleValues instead of doubles

- css-typed-om/Overview.bs
> [css-typed-om] Remove double constructors for CSSRotation and CSSSkew

- css-layout-api/README.md
> [css-layout-api] fix typo

- css-typed-om/Overview.bs
(https://github.com/w3c/css-houdini-drafts/issues/192)
> [css-typed-om] clarify how CSSUnparsedValues compute.

- font-metrics-api/Overview.bs
Initial proposal for a v1 font metrics api. Includes both in-document and out-of-document measurements. The FontMetrics object is loosely based on the canvas measureText TextMetrics one.
> [font-metrics-api] Initial FontMetrics draft

- css-typed-om/Overview.bs
Fixes https://github.com/w3c/css-houdini-drafts/issues/322
> [css-typed-om] Rename CSSFontFaceValue.fontFaceName to fontFamilyName

- css-layout-api/EXPLAINER.md
Sorry for the mini-patch, I just spotted that and thought it was worth to fix.
> [css-layout-api] Fix typo where the wrong variable was accessed.

- css-paint-api/Overview.bs
E.g.
registerPaint('foo', class {
static get inputArguments() { return ['<length>']; }
paint(ctx, size, styleMap, arguments) {
}
});
Fixes #100.
> [css-paint-api] Adds paint function arguments.

- worklets/Overview.bs
Instead of relying on "in parallel" this change makes all the thread
hopping explicit via. message passing and queue tasks on the appropriate
event loop.
- Fixes #372, changes arguments to fetch a module script graph.
- Fixes #370, running scripts in parallel. Now the script explicitly are
run within a task queued on the worklet global scope's event loop.
- Fixes #318, actually runs the event loop.
- Fixes #230, treats "fetch a module worker script graph" as
asynchronous.
- Fixes #377, as now performs a thread hop to create the workletglobalscope.
- Probably fixes #225 ? I think I'm grabbing the correct state at each
thread hop.
> [worklets] Multiple fixes to the {{Worklet/import()}} algorithm.

- worklets/Overview.bs
This changes the import() method to optionally accept a credentials
argument, e.g.
CSS.paintWorklet.import('paint.js', {credentials: 'include'});
> [worklets] Create WorkletOptions dictionary to pass through credentials.

- worklets/Overview.bs
Fixes #384.
Fixes #308. (There is a separate issue for adding the 2
WorkletGlobalScopes requirement for css-paint-api).
> [worklets] Reworks "Code Idempotency" section.

- css-typed-om/Overview.bs
@shans could you take a look?
This hopefully adds the text needed for issue #404
> Fix issue 404

- css-properties-values-api/Overview.bs
Was causing a Bikeshed error message.
> [css-properties-values-api] Fix indentation in note about transform-list.

- css-typed-om/Overview.bs
(#312) `background-position` is a shorthand so it should not be a `CSSPositionValue`. Replaced it with `object-position` which is a longhand `<position>` property.
@shans PTAL?
> [css-typed-om] Replace background-position with object-position

- css-typed-om/Overview.bs
This change is to address issue 149 (https://github.com/w3c/css-houdini-drafts/issues/149). The conclusion  reached at W3C meeting was that computed, declared and inline StylePropertyMap should all be live objects. This change puts in the conclusion.
> StylePropertyMaps are live objects.

- css-typed-om/Overview.bs
Fix for issue #145 - @shans could you PTAL?
> Refactor out value type-checking logic from CSSStyleValue.append to fix issue #145

- css-typed-om/Overview.bs
@shans  PTAL this fixes #424. 
Also didn't know if we should mention anything about the behaviour in a PaintWorklet. Left it out for now.
> Add description for CSSURLImageValue constructor.

- css-typed-om/Overview.bs
This adds a description for StylePropertyMapReadOnly.delete() which is mentioned in #148. 
@shans PTAL? Thanks!
> Add description for StylePropertyMapReadOnly.delete()

- css-typed-om/Overview.bs
This adds a description for StylePropertyMapReadOnly.set() which is mentioned in #148 
@shans  PTAL? Thanks!
> Add description for StylePropertyMapReadOnly.set()

- css-typed-om/Overview.bs
@shans PTAL? This adds a description for get() which is one of the functions mentioned in #148. 
Will do the other functions in different CLs.
> Add description for StylePropertyMapReadOnly.get()

- css-typed-om/Overview.bs
@shans PTAL? This adds a description for has() which is one of the functions mentioned in #148.
Will do the other functions in different CLs.
> Add description for StylePropertyMapReadOnly.has()

- css-typed-om/Overview.bs
(#350) Renames `Element.styleMap` to `Element.attributeStyleMap` and `Window.getComputedStyleMap` to `Element.computedStyleMap`. @shans  PTAL
> [css-typed-om] #350 Rename styleMap and getComputedStyleMap

- css-paint-api/Overview.bs
Per discussion here: https://github.com/w3c/css-houdini-drafts/issues/436, CSS working group agreed to add a devicePixelRatio property to the PaintRenderingContext2D.
@bfgeek Please review.
> Add devicePixelRatio property to PaintRenderingContext2D

- css-paint-api/Overview.bs
@bfgeek @flackr: Please review.
> Replace alpha flag with a PaintRenderingContext2DSettings object

- css-typed-om/Overview.bs
tabatkins@ PTAL? 
Fixes issue #325
> Clean up CSSNumericValue.equals and remove assumption in last step.

- css-typed-om/Overview.bs
Track #482 in the spec text.
@nainar
> [css-typed-om] Track issue 482

- css-typed-om-2/Overview.bs
- css-typed-om/Overview.bs
Issue #310 was resolved to be moved to css-typed-om 2, so we can remove it from the L1 spec.
@shans PTAL?
> [css-typed-om] Remove issue #310 from text.

- css-properties-values-api/Overview.bs
Remove the unwanted linking default for "ascii case-insensitive". It's in [Infra](https://infra.spec.whatwg.org/#ascii-case-insensitive) now, and Bikeshed can autolink to the dfn.
> [css-properties-values-api] Bikeshed fix

- css-paint-api/Overview.bs
It was pointed out here: https://github.com/w3c/css-houdini-drafts/issues/479, that the spec says to "Set bitmap dimensions for the context’s output bitmap to width and height", which implies that the width and height are integers.
This pull request makes change to say rounded values of width and height, which makes it explicit.
> [PaintWorklet] Explicit state the PaintSize could be fractional

- css-typed-om/Overview.bs
> Remove CSSMathValue.type

- css-typed-om/Overview.bs
git branching magic - couldn't seem to merge these two pull requests. (due to a change in the branch name)
Adding Tab's comments on the previous patch here:
"from wasn't turned into to; from was the more generic factory function. It was replaced by parse in the first instance, and the CSSUnitValue constructor in the second instance (or CSS.px())."
Closing the other PR
> Remove references to CSSNumericValue.from() in the spec

- css-paint-api/Overview.bs
- worklets/Overview.bs
Currently, user agents can only invoke worklets with consistent snapshots of the state. This PR allows user agents to invoke worklet scripts with inconsistent state, as long as they discard the result.
The particular instance of this is paint worklets, since the CSS style values are known before the concrete size, so in Servo we speculate that the size hasn't changed (https://github.com/servo/servo/pull/17810).
Fixes #406.
> Allow speculative evaluation

- css-typed-om/Overview.bs
Fixes #504 
CSS.Hz and CSS.kHz already had the correct case.
@tabatkins PTAL?
> rename CSS.q() to CSS.Q()

- css-layout-api/Overview.bs
`<<display-inside>>` isn't a property, so you cannot use a propdef table
to extend it (and incidentally, that made bikeshed generate some
garbage).
Explicitly extend the `<<display-inside>>` production instead.
This commit does not change the intended meaning of the normative prose,
merely defines it more correctly, and should therefore be considered
editorial.
> [css-layout-api] Fix incorrect extension of <<display-inside>>

- css-typed-om/Overview.bs
Should fix issue #522 
@tabatkins PTAL when you have time
> Change CSSPositionValue normalization to use auto bias

- css-typed-om/Overview.bs
Resolves #553 
@tabatkins PTAL, thanks!
> [css-typed-om] Restrict unsupported CSSStyleValues to the property that it was parsed with

- css-typed-om/Overview.bs
Resolves #305 
@tabatkins PTAL? Thanks!
> Change parse/parseAll to throw TypeError

- css-typed-om/Overview.bs
Resolves #503 
@tabatkins PTAL. Wording for `mul` might be a bit awkward.
> [css-typed-om] Add shortcuts for other arithmetic operations

- css-typed-om/Overview.bs
> Expand CSSOM to Cascading Style Sheets Object Model at start of spec

- css-typed-om/Overview.bs
Issue #516 
@tabatkins PTAL, thanks.
> [css-typed-om] Change CSSMathNegate type to same as its argument.

- css-paint-api/Overview.bs
- css-paint-api/circle/index.html
Fix a typo in example code to match [PropertyDescriptor definition](https://drafts.css-houdini.org/css-properties-values-api/#registering-custom-properties)
> [css-paint-api] Typo in registerProperty: inherit -> inherits

- css-typed-om/Overview.bs
Fixes #578 and #520 by defining the product of two unit maps separately.
> Clarify the union of two unit maps

- css-typed-om/Overview.bs
1. Replace CSSStyleRule.attributeStyleMap-> CSSStyleRule.styleMap
2. Clarify that the attribueStyleMap on Element is actually on ElementCSSInlineStyle interface
Fixes #572
> Sanitize the declared and inline StylePropertyMaps

- css-typed-om/Overview.bs
issue #482 
Hi @tabatkins, PTAL. I'm not sure if I'm doing this right, so I only wrote up the interface for now. I'll do the actual text once we've agreed on the interface.
> Add wording for CSSNumericValue.type()

- css-typed-om/Overview.bs
> CSSStyleValue.parseAll should always return a list

- css-typed-om/Overview.bs
> define a valid CSS property in Typed OM spec

- css-typed-om/Overview.bs
> CSSNumericValue.parse() allows {max,min,calc}()

- css-typed-om/Overview.bs
> Remove references to case sensitivity in StylePropertyMap definition

- css-typed-om/Overview.bs
Removes references to `FontFaceValue`, which has been pushed to level 2.
> Remove references to font face

- css-typed-om/Overview.bs
Fixes #487 (I think).
Hi @tabatkins, PTAL
> Use indexed getters for CSSTransformComponent

- css-typed-om/Overview.bs
Fixes #494
Hi @tabatkins, PTAL
> Make CSSNumericValue members readonly

- css-typed-om/Overview.bs
Closes #239 , Looks like `CSSUnparsedValue` already uses indexed getters, so we can just remove the issue note from the spec?
> Use indexed getters for CSSUnparsedValue

- css-typed-om/Overview.bs
> CSSPositionValue normalization should not imply parsing

- css-typed-om/Overview.bs
issue #514 
Also makes `CSSVariableReferenceValue.fallback` readonly.
Hi @tabatkins, PTAL.
> Add constructor to CSSVariableReferenceValue

- css-typed-om/Overview.bs
> CSSVariableReferenceValue.variable setter rejects invalid variable names

- css-typed-om/Overview.bs
Fixes #612 . Changes behaviour: you can no longer pass in an option with null `is2D`.
> Use defaults for CSSMatrixComponentOptions

- css-typed-om/Overview.bs
> Add CSSTransformComponent.is2D

- README.markdown
See https://github.com/foolip/testing-in-standards/blob/master/policy.md
for context. This phrasing matches that used for many other specs'
CONTRIBUTING.md files, in particular:
https://github.com/w3c/fxtf-drafts/blob/master/CONTRIBUTING.md#tests
https://github.com/w3c/csswg-drafts/blob/master/CONTRIBUTING.md#tests (slightly different)
> Ask for tests for normative changes in README

- css-typed-om/Overview.bs
Adds instructions to serialize the opacity property.
@shans PTAL?
> [css-typed-om] Add serialization for 'opacity'

- css-typed-om/Overview.bs
Fixes #616 .
Hi @tabatkins , PTAL.
> Add validation to CSSVariableReferenceValue constructor

- css-typed-om/Overview.bs
Fixes #566 ? Not quite sure how to do this. How a "CSS production" matches a "grammar" is a bit handwavy.
Hi @tabatkins , PTAL.
> Extend match concept to other style values

- css-typed-om/Overview.bs
Fixes #576 . Tries to clarify `CSSNumericValue.equals` a bit by pulling pairwise equality into its own algo.  Not quite sure if this is idiomatic bikeshed.
Hi @tabatkins PTAL
> Clarify CSSNumericValues.equals

- css-typed-om/Overview.bs
> Example 7 - queries computedStyleMap() instead of specified attributeStyleMap

- css-typed-om/Overview.bs
> Reference CSSPositionValue normalization where relevant

- css-typed-om/Overview.bs
> Remove redundant reference to exit this algorithm

- css-typed-om/Overview.bs
> Clarify inverse to be multiplicative inverse.

- css-typed-om/Overview.bs
> Remove StylePropertyMap.update()

- css-typed-om/Overview.bs
Should fix #663 #666 #667 
Hi @bzbarsky , PTAL? The language for indexed getter/setter is still a bit handwavy :P Thanks!
> Clarify CSSUnparsedValue and CSSVariableReferenceValue.

- css-typed-om/Overview.bs
Reverts #613 and fixed typo.
Hi @tabatkins PTAL.
> Revert back to no defaults for CSSMatrixComponentOptions.is2D

- css-typed-om/Overview.bs
Fixes #660 . 
Hi @tabatkins PTAL. Not sure how to write it explicitly in the algorithm (how to "cache" it?)
> computedStyleMap() must return same object

- css-typed-om/Overview.bs
Hi @tabatkins , PTAL. I got some questions too.
> Add font reification

- css-paint-api/Overview.bs
This pull request address the issue here:
https://github.com/w3c/css-houdini-drafts/issues/508
Basically, instead of passing the concrete object size to the paint function, we let it pass the round(concrete object size) / device pixel ratio.
Please review. @bfgeek @flackr
> [CSS Paint API] Pass snapped concrete size to paint function

- worklets/Overview.bs
This changes the default credentials mode from 'omit' to 'same-origin'.
Issue: #756
> [worklets] Change the default credentials mode

- css-paint-api/Overview.bs
While adding a test in https://github.com/web-platform-tests/wpt/pull/9773 it highlighted the incorrect IDL. `CanvasState` etc are `interface mixin`, not `interface`, so are to be `includes` not `implements`.
> Fix mixin keyword in IDL

- css-layout-api/Overview.bs
> Fix typo "auther" -> "author"

- css-properties-values-api/Overview.bs
> [css-properties-values-api] Describe font-relative unit cycles.

- css-properties-values-api/Overview.bs
The current text doesn't actually mention what should happen with
`<transform-function>` values that do NOT appear in `<transform-list>`.
> [css-properties-values-api] Clarify computed value of <transform-function>

- css-properties-values-api/Overview.bs
We have multiple list types now, so let's be unambiguous.
> [css-properties-values-api] Clarify list type in Example 3.

- css-properties-values-api/Overview.bs
Values with `<image>` syntax can contain lengths, for example:
linear-gradient(red 1em, blue);
> [css-properties-values-api] Resolve lengths for <image> values.

- css-layout-api/Overview.bs
- css-paint-api/Overview.bs
- css-properties-values-api/Overview.bs
CSSOM and other CSS specs were updated in https://github.com/w3c/csswg-drafts/pull/437.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=29623.
> [css-layout-api][css-paint-api][css-properties-values-api] Use partial namespace CSS

- css-layout-api/Overview.bs
Fixes https://github.com/w3c/css-houdini-drafts/issues/758.
> [css-layout-api] Make BreakToken#childBreakTokens a FrozenArray

- box-tree-api/Overview.bs
Web IDL does not allow attributes to be of type sequence<T>.
> [box-tree-api] Change children attribute from sequence<T> to FrozenArray<T>

- css-animationworklet/Overview.bs
- css-animationworklet/README.md
Since migration from wicg/animation-worklet two PRs have been merged to the original repo.
This PR contains the two commits (cherry-picked).
Original commits:
* https://github.com/WICG/animation-worklet/commit/76429c78bc06897e84afcdd86fc326c68d777b21
* https://github.com/WICG/animation-worklet/commit/0ada999a2573ca35f6c4e36bd1e7377de51744ee
> [css-workletanimation] merge changes from original repo since migration

- css-animationworklet/Overview.bs
- css-animationworklet/README.md
The upstream spec has changed to include scrollSource in options dictionary.
> [css-animationworklet] update ScrollTimeline usage in examples

- css-animationworklet/README.md
- css-animationworklet/principles.md
- css-animationworklet/status.md
- css-animationworklet/vision.md
Adding a vision document to the repository. Hopefully this help clarify the principles for AnimationWorklet. In particular, I have listed few expansion direction that we could pursue to help develop and direct the full vision of AnimationWorklet.
Also added a rough road for the feature implementation in Chrome which should help anyone planning  to plan to experiment with it.
> [css-animationworklet] Add a vision document and rough Chrome roadmap

- css-animationworklet/Overview.bs
Fixes issue #812 .
- Introduce two new interfaces `StatefulAnimator` and `StatelessAnimator`. Add sections to describe the difference.
- Update Animator Definition to has stateful flag and initialize the flag based on the animator prototype object.
- Update the algorithm for migration process to not use onDestroy callback but use state getter.
- Update the examples to use these new interfaces and show how getter should be used.
> [css-animationworklet] Separate Stateful and Stateless animator interfaces  #812

- css-properties-values-api/Overview.bs
> [css-properties-values-api] Canonical units for computed values, etc.

- font-metrics-api/Overview.bs
Per https://heycam.github.io/webidl/#idl-sequence, "Sequences must
not be used as the type of an attribute or constant."
> [font-metrics-api] Convert sequence<T> attributes to FrozenArray<T>

- css-properties-values-api/Overview.bs
This defines how to parse the syntax strings using some algorithms and
concepts from css-syntax, while leaning as little as possible on its
concept of tokens.
* Whitespace behavior is now defined.
* Escaping is now allowed for ident syntax strings.
Resolves #112.
> [css-properties-values-api] Define parsing rules for the syntax string.

- css-layout-api/Overview.bs
This was invalid Web IDL. Also make it optional since there are no required members.
> [css-layout-api] Name the FragmentResultOptions argument

- css-properties-values-api/Overview.bs
The current text allows syntax strings like "|&lt;color>", which seems pretty
pointless.
> [css-properties-values-api] Disallow leading '|' in syntax strings.

- css-animationworklet/Overview.bs
There is no need for state to be a getter rather than a function.
It is simpler to implement and more consistent with `animate()` for state to also be a function.
> [css-animationworklet] Change state to be a function instead of getter

- css-typed-om/Overview.bs
https://drafts.csswg.org/cssom/#the-elementcssinlinestyle-interface is an
interface mixin, and the partial must match this. Update the prose to reflect
this as well.
> [css-typed-om] Use `partial interface mixin ElementCSSInlineStyle`

- css-properties-values-api/Overview.bs
* Define how setProperty() behaves for registered custom properties.
* Define how values reify.
* How underlying values are created is not defined, as I _think_ the
current description in css-typed-om covers it.
> [css-properties-values-api] Define effects on CSSOM.

- css-properties-values-api/Overview.bs
"Consume a name" doesn't return an `<ident-token>`. Also, it seems more
clean to avoid css-syntax's tokens if we can.
> [css-properties-values-api] "Consume a name" returns a string.

- css-properties-values-api/Overview.bs
Something like this was in the original syntax parsing PR, but it got
lost at some point.
Resolves #879.
> [css-properties-values-api] Require <custom-ident> as component name.

- css-animationworklet/Overview.bs
Drop multiple timelines and relevant concepts for Animation Worklet.
This also drops the hide-bar example from spec. I may re-work this example (e.g., switching timeline via setting animation.timeline on main thread)  and add it back this in future but for now dropping it is simpler.
Multiple timeline was originally the solution that would allow seamless switching between between
scroll timeline and regular timelines. Since then we have iterated over multiple different solutions.
See #834 for a list of various design we have considered. It seems that allowing events to be handled
in Animation Worklets will enable the relevant usecases. 
For now we drop multiple timelines fromAnimation Worklet Level-1 to ensure simplicity and better alignment with WebAnimations.
> [css-animationworklet] Remove multiple timelines

- css-properties-values-api/Overview.bs
> [css-properties-values-api] Fix syntax string parsing to not treat whitespace between components the same as pipes.

- css-properties-values-api/Overview.bs
Resolves #897.
Note: bikeshed claims css-conditional-3 doesn't exist (by that name), which seems to be correct.
cc @tabatkins
> [css-properties-values-api] Reify '*' and direct CSSStyleValues properly.

- css-animationworklet/Overview.bs
- css-animationworklet/README.md
The Animation Worklet  does not require or depend on the worklet running in a parallel execution context. In another word, it is valid and reasonable to run Animation Worklet  on the main rendering thread. Similar to other Houdini primitives, the worklet is allowed to run on a different thread. This is an implementation detail that engine can take advantage of to improve animation smoothness.
Given that threading model is an implementation detail, I move most of that discussion to the Explainer. 
The only aspect of that is relevant to the specification is "async" nature of worklet animation timing model (which enables the parallel execution mode). This is already discussed in "Worklet Animation timing model" and thus I moved the discussion of valid main thread sync opportunities for …
> [css-animationworklet] Move threading model out of spec and into README

- css-properties-values-api/Overview.bs
> [css-properties-values-api] Generally ignore syntax in APIs.

- css-properties-values-api/Overview.bs
Using 'descriptor' is very confusing since we're going to introduce
`@property`, which has descriptors in the at-rule sense.
Especially "syntax descriptor" is confusing when we're adding an at-rule
descriptor named 'syntax'.
> [css-properties-values-api] Avoid the term 'descriptor'.

- css-properties-values-api/Overview.bs
This adds basic support for `@property`, without solving any of the potentially complicated issues, like #845 and #846.
Resolves #137, at least partially.
> [css-properties-values-api] Add @property.

- css-paint-api/Overview.bs
- css-properties-values-api/Overview.bs
The css-properties-values-api now describes in detail how to produce a
"syntax descriptor" from a string, so it's better to link to that rather
than linking to a section in the spec.
> [css-paint-api] Lean on "syntax definition" concept.

- css-animationworklet/Overview.bs
I still think we need more work in this area but 
- Update web-animations spec link to be https://drafts.csswg.org which is more recent
- Improve wording on how worklet animation interacts with web-animations
- Add section to deal with addition of "replace state" in Web animations.
- lots of small fixes
- Add issue to indicate our current shortcoming for async operations.
> Improve wording on web-animation integrations

- worklets/Overview.bs
> [worklets] Reject with script's error to rethrow

- worklets/Overview.bs
This is a follow-up patch for #958. A task to reject addModule() should
be queued with script's error to rethrow to run on the thread where
addModule() is called.
This fixes #509
> [worklets] Queue a task to reject addModule()

- css-paint-api/Overview.bs
> [css-paint-api-1] Fix typo

- worklets/Overview.bs
Follows https://github.com/whatwg/html/pull/5411.
This moves to the imperative style of agent allocation, as HTML is no longer declaratively defining worklet agents and saying that they must be implicitly created at the appropriate time.
> [worklets] Update agent and realm allocation

- css-typed-om/README.md
CSSPositionValue was removed from the spec in https://github.com/w3c/css-houdini-drafts/commit/5261c1a.
> Drop CSSPositionValue from README.md

- css-properties-values-api/Overview.bs
- Emit 'initial-value', not 'initialValue'.
- Do not emit a space after 'initial-value:', since it prepends the space to the initial value when round-tripping.
> [css-properties-values-api] Fix initial-value serialization

- css-paint-api/Overview.bs
- worklets/Overview.bs
> [worklets] Adds hook for downstream spec to set the destination.

- worklets/Overview.bs
HTML has yet again changed the fields in settings objects.
Closes #992 by superseding it. Part of https://github.com/whatwg/fetch/issues/1062.
> [worklets] Update global object allocation

- css-typed-om/Overview.bs
This currently causes IDL parser failure.
> [css-typed-om] Add missing parentheses for union

- css-typed-om-2/Overview.bs
Bikeshed was trying to render them as regular HTML elements
> [css-typed-om-2] Double bracket non-elements

- css-properties-values-api/Overview.bs
- Export "registered custom property".
- Export "universal syntax definition".
- Fix a "the the".
- When parsing against the syntax, we probably want "invalid at
computed-value time", not guaranteed-invalid?
Somewhat related to: https://github.com/w3c/csswg-drafts/issues/5370
> [css-properties-values-api-1] Export registered custom property, etc

- css-layout-api/Overview.bs
Per Web IDL, no extended attributes are applicable to dictionaries/enumerations:
https://heycam.github.io/webidl/#idl-dictionaries
https://heycam.github.io/webidl/#idl-enums
> Removed [Exposed] from dictionary/enum

- css-typed-om/Overview.bs
> Add type checking to `CSSNumericValue.parse`

- css-typed-om/Overview.bs
Step 2 of  parse()  [1] says "Reify a color value from  result ".
However, "Reify a color value" algorithm [2] needs a second parameter,
which is a property to be consumed by step 9 only.
Therefore, Change step 9 from 'CSSStyleValue' to 'an identifier'[3] for reifying.
And the reify a color value algorithm no more need |prop|.
Hence, Remove the |prop| parameter of 'reifying a color value'.
[1] https://drafts.css-houdini.org/css-typed-om-1/#dom-csscolorvalue-parse
[2] https://drafts.css-houdini.org/css-typed-om-1/#reify-a-color-value
[3] https://drafts.css-houdini.org/css-typed-om-1/#reify-an-identifier
Working Chromium CL: https://chromium-review.googlesource.com/c/chromium/src/+/3522201
csswg issue: https://github.com/w3c/csswg-drafts/issues/7174
cc. @xiaochengh
> [CSS-Typed-OM] Change reifying as from 'a CSSStyleValue' to 'an identifier'

- css-typed-om/Overview.bs
https://github.com/whatwg/webidl/issues/60 has been fixed for a long time.
> [css-typed-om] use undefined union value for StylePropertyMapReadOnly.get()

- css-typed-om/Overview.bs
Add missing cap / rcap / rch / rex / ric units.
Fixes #1106.
> [css-typed-om] Add missing font units to CSS numeric factory

- css-properties-values-api/Overview.bs
> [css-properties-values-api] Specify <string> syntax component name

- css-properties-values-api/Overview.bs
The "URL behavior examples" contained a typo where the used variable in the `<div>`'s `style` attribute had 3 dashes (`-`) instead of 2.
> [css-properties-values-api] Fix typo in URL example

- css-layout-api/Overview.bs
- css-paint-api/Overview.bs
Rethrowing is no longer implicit (since reporting is frequently what's desired). Here handling the exception is intended, so this is a very small change.
Also included are the various changes required to make these specs build and fixes to some places nearby where a clearly incorrect definition was linked to.
Part of whatwg/webidl#1425.
> Editorial: Update use of WebIDL "invoke a callback function"

- css-properties-values-api/Overview.bs
There is no corresponding test on [WPT](https://github.com/web-platform-tests/wpt/blob/master/css/css-properties-values-api/register-property-syntax-parsing.html) but empty string is a valid [`initial-value`](https://drafts.css-houdini.org/css-properties-values-api-1/#initial-value-descriptor), and `CSS.registerProperty({ ..., syntax: '*', initialValue: '' })` works on current version of Chrome and FF.
> [css-properties-values-api-1][editorial] Match an empty string for initialValue

- css-properties-values-api/Overview.bs
Resolves https://github.com/w3c/csswg-drafts/issues/10455.
> [css-properties-values-api] Make var() fallback type-agnostic

- css-typed-om/Overview.bs
Fixes #1142
See also https://github.com/whatwg/webidl/issues/1516
> [css-typed-om] Use undefined for setters.

- css-typed-om/Overview.bs
Closes #1144.
(Should be non-substantive.)
> [css-typed-om-1] Correct `this` type in StylePropertyMapReadOnly methods
